# Generated by Django 2.1.2 on 2018-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
